import {
  Accessibility,
  Armchair,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Bath,
  Bed,
  BedDouble,
  Bell,
  Blocks,
  BookA,
  BookOpen,
  Building,
  Building2,
  Bus,
  CalendarCheck,
  Car,
  CarTaxiFront,
  ChartPie,
  CircleDollarSign,
  CirclePlus,
  ClipboardCheck,
  Clock,
  ClockArrowDown,
  ConciergeBell,
  DoorOpen,
  Eye,
  FileText,
  Flag,
  Folder,
  FolderTree,
  Fuel,
  Gift,
  GitBranch,
  History,
  Hotel,
  Image,
  Images,
  LayoutGrid,
  Leaf,
  ListTree,
  MapPinHouseIcon,
  MapPinned,
  MessageCircleMore,
  MessageCircleQuestionMark,
  MessageCircleWarning,
  MonitorCog,
  Mountain,
  Network,
  Package,
  Plane,
  PlaneLanding,
  PlusCircle,
  Receipt,
  Route,
  Scale,
  ScrollText,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Ship,
  ShoppingCart,
  Sofa,
  Soup,
  Star,
  Tag,
  Ticket,
  User,
  UserCog,
  Users,
  Utensils,
  UtensilsCrossed,
} from "lucide-react";

export const SIDEBARCONTENTICONS = {
  user: User,
  plane: Plane,
  bus: Bus,
  car_taxi_front: CarTaxiFront,
  hotel: Hotel,
  yacht: Ship,
  plane_landing: PlaneLanding,
  chart_pie: ChartPie,
  user_cog: UserCog,
  circle_dollar_sign: CircleDollarSign,

  building_2: Building2,
  building: Building,

  map_pin_house: MapPinHouseIcon,
  map_pinned: MapPinned,

  search: Search,
  clock: Clock,
  book_a: BookA,

  // =====================
  // HOTEL
  // =====================

  badge_check: BadgeCheck,

  star: Star,

  leaf: Leaf,

  bed: Bed,
  bed_double: BedDouble,

  door_open: DoorOpen,

  bath: Bath,

  mountain: Mountain,

  image: Image,

  layout_grid: LayoutGrid,

  accessibility: Accessibility,

  utensils: Utensils,

  utensils_crossed: UtensilsCrossed,

  soup: Soup,

  bell: Bell,

  gift: Gift,

  file_text: FileText,

  receipt: Receipt,

  shield_check: ShieldCheck,
  folder: Folder,
  blocks: Blocks,
  shield: Shield,
  armchair: Armchair,
  ship: Ship,
  clipboard_check: ClipboardCheck,
  users: Users,
  sofa: Sofa,
  clock_alert: ClockArrowDown,
  network: Network,
  book_open: BookOpen,
  tags: Tag,
  fuel: Fuel,
  route: Route,
  concierge_bell: ConciergeBell,
  car: Car,
  shopping_cart: ShoppingCart,
  calendar_check: CalendarCheck,
  list_tree: ListTree,
  plus_circle: PlusCircle,
  badge_dollar_sign: BadgeDollarSign,
  badge_percent: BadgePercent,
  git_branch: GitBranch,
  ticket: Ticket,
  package: Package,
  circle_plus: CirclePlus,
  folder_tree: FolderTree,
  scroll_text: ScrollText,
  images: Images,
  message_circle_question_mark: MessageCircleQuestionMark,
  message_circle_warning: MessageCircleWarning,
  message_circle_more: MessageCircleMore,
  scale: Scale,
  shield_off: ShieldOff,
  shield_alert: ShieldAlert,
  flag: Flag,
  settings: Settings,
  history:  History,
  settings_2: Settings2,
  monitor_cog: MonitorCog
} as const;
