export const API = {
  AUTH: "/auth",

  USER: "/user",

  PROVIDER_BOOKING: "/provider-booking",
  METRICS:"/metrics",

  MEDIA_CATEGORY: "/media-category",
  MEDIA_ASSET: "/media-asset",
  AUDIT_LOG: "/audit-log",
  SYSTEM_SETTING: "/system-setting",

  REASON_CODE: "/reason-code",
  REASON_CONTEXT: "/reason-context",
  LEGAL_DOCUMENT: "/legal-document",
  REGULATION: "/regulation",
  REGULATION_CATEGORY: "/regulation-category",
  TAX_RULE: "/tax-rule",
  FEATURE_FLAG: "/feature-flag",
  WHITELIST_ENTRY: "/whitelist-entry",
  BLACKLIST_ENTRY: "/blacklist-entry",

  // Hotel
  HOTEL: "/hotel",
  HOTEL_ACCESSIBILITY: "/hotel-accessibility",
  HOTEL_BATHROOM_TYPE: "/hotel-bathroom-type",
  HOTEL_BED_TYPE: "/hotel-bed-type",
  HOTEL_DINING_MEAL_TYPE: "/hotel-dining-meal-type",
  HOTEL_DINING_SERVICE_TYPE: "/hotel-dining-service-type",
  HOTEL_EXTRA_TYPE: "/hotel-extra-type",
  HOTEL_BRAND: "/hotel-brand",
  HOTEL_RATE_PLAN_TYPE: "/hotel-rate-plan-type",
  HOTEL_STAR_RATING: "/hotel-star-rating",
  HOTEL_TYPE: "/hotel-type",
  HOTEL_MEAL_PLAN: "/hotel-meal-plan",
  HOTEL_ROOM_CATEGORY: "/hotel-room-category",
  HOTEL_ROOM_VIEW: "/hotel-room-view",
  HOTEL_SUSTAINABILITY: "/hotel-sustainability",
  HOTEL_ROOM_TYPE: "/hotel-room-type",
  HOTEL_CHECK_IN_POLICY: "/hotel-check-in-policy",

  FACILITY: "/facility",
  FACILITY_CATEGORY: "/facility-category",

  PROMOTION: "/promotion",
  COUPON: "/coupon",

  EXTRA_TYPE: "/extra-type",

  BOOKING_TYPE: "/booking-type",

  CITY: "/city",

  COUNTRY: "/country",
  ADDRESS: "/address",
  CURRENCY: "/currency",

  // AIRPORT: "/airport",

  AIRPORT_TRANSFER: "/airport-transfer",
  AIRPORT_TRANSFER_PRICE_RULE_TYPE: "/airport-transfer-price-rule-type",
  AIRPORT_TRANSFER_ROUTE_TYPE: "/airport-transfer-route-type",
  AIRPORT_TRANSFER_SERVICE_TYPE: "/airport-transfer-service-type",

  CAR_RENTAL: "/car-rental",
  CAR_RENTAL_INSURANCE_BENEFIT_TYPE: "/car-rental-insurance-benefit-type",
  CAR_RENTAL_INSURANCE_TYPE: "/car-rental-insurance-type",
  CAR_RENTAL_DOCUMENT_TYPE: "/car-rental-document-type",

  BUS: "/bus",
  BUS_SEAT_TYPE: "/bus-seat-type",

  YACHT: "/yacht",
  YACHT_CONDITION: "/yacht-condition",
  YACHT_CREW_ROLE: "/yacht-crew-role",
  YACHT_EXTRA_CATEGORY: "/yacht-extra-category",
  YACHT_FEE_TYPE: "/yacht-fee-type",
  YACHT_SERVICE_TYPE: "/yacht-service-type",
  YACHT_TYPE: "/yacht-type",

  FLY: "/ticket-fly",
  FLY_AIRPORT: "/ticket-fly-airport",
  FLY_ADDON_TYPE: "/fly-fly-addon-type",
  FLY_CABIN_CLASS: "/ticket-fly-cabin-class",
  FLY_CREW_DUTY: "/fly-crew-duty",
  FLY_CREW_ROLE: "fly-crew-role",
  FLY_DELAY_REASON: "/ticket-fly-delay-reason",
  FLY_FARE_RULE_TYPE: "/ticket-fly-fare-rule-type",
  FLY_MEAL_TYPE: "/ticket-fly-meal-type",
  FLY_PRICE_RULE_TYPE: "/ticket-fly-price-rule-type",
  FLY_SEAT_TYPE: "/ticket-fly-seat-type",
  FLY_AIRCRAFT: "/aircraft",
  FLY_ALLIANCE: "/alliance",
  FLY_AIRLINE: "/airline",
  FLY_CREW: "/fly-crew",
  FLY_AIRCRAFT_TYPE: "/aircraft-type",

  VEHICLE_TYPE: "/vehicle-type",
  ROUTE_TYPE: "/route-type",
  SERVICE_TYPE: "/service-type",
  PRICE_RULE_TYPE: "/price-rule-type",
  BOOKING_ITEM_TYPE: "/booking-item-type",

  FUEL_TYPE: "/fuel-type",
  EXTRA: "/extra",
  EXTRA_FEE_TYPE: "/extra-fee-type",
  PACKAGE: "/package",
  POLICY: "/policy",
  POLICY_TYPE: "/policy-type",
  PROMOTION_RULE: "/promotion-rule",
  CONTINENT: "/continent",
  PLACE_TYPE: "/place-type",

  WARD: "/ward",
  DISTRICT: "/district",
  TIMEZONE: "/timezone",
  LANGUAGE: "/language",
  PLACE: "/place",
  TAG: "/search-tag",
} as const;
