export const airportTransferFieldGroups = {
  basic: [
    "providerBookingId",
    "name",
    "serviceType",
    "instantConfirmation",
    "active",

    "searchPriority",
    "featured",
    "searchable",
    "tagIds",

    "capacity.maxTripsPerDay",
    "capacity.maxVehiclesPerDay",
    "capacity.overbookingAllowed",

    "notice.title",
    "notice.color",
    "notice.icon",
    "notice.priority",
    "notice.active",
    "notice.description",
  ] as const,

  route: [
    "routes.0.type",
    "routes.0.departureAddressId",
    "routes.0.arrivalAddressId",
    "routes.0.distanceKm",
    "routes.0.estimatedDuration",
    "routes.0.active",

    "routes.0.stops.0.addressId",
    "routes.0.stops.0.stopOrder",
    "routes.0.stops.0.estimatedArrival",
    "routes.0.stops.0.waitingMinutes",

    "schedules.0.departureTime",
    "schedules.0.startDate",
    "schedules.0.endDate",
    "schedules.0.active",
    "schedules.0.operatingDays",
  ] as const,

  vehicle: [
    "vehicle.0.type",
    "vehicle.0.name",
    "vehicle.0.manufacturer",
    "vehicle.0.model",
    "vehicle.0.year",
    "vehicle.0.color",
    "vehicle.0.licensePlate",
    "vehicle.0.transmission",
    "vehicle.0.fuelType",
    "vehicle.0.status",

    "vehicle.0.capacity.passengerCount",
    "vehicle.0.capacity.luggageCount",
    "vehicle.0.capacity.cabinBaggageCount",
    "vehicle.0.capacity.oversizedLuggage",

    "vehicle.0.features.airConditioner",
    "vehicle.0.features.wifi",
    "vehicle.0.features.usbCharger",
    "vehicle.0.features.bottledWater",
    "vehicle.0.features.childSeat",
    "vehicle.0.features.wheelchairAccessible",
    "vehicle.0.features.petFriendly",
    "vehicle.0.features.phoneCharger",
    "vehicle.0.features.music",
    "vehicle.0.features.gpsTracking",

    "vehicle.0.specification.engineSizeCc",
    "vehicle.0.specification.fuelCapacity",
    "vehicle.0.specification.mileageKm",
    "vehicle.0.specification.vin",

    "vehicle.0.images.0.url",
    "vehicle.0.images.0.category",
    "vehicle.0.images.0.isPrimary",
    "vehicle.0.images.0.sortOrder",
    "vehicle.0.images.0.alt",

    "vehicle.0.availability.0.startDate",
    "vehicle.0.availability.0.endDate",
    "vehicle.0.availability.0.available",
    "vehicle.0.availability.0.note",

    "vehicle.0.drivers.0.firstName",
    "vehicle.0.drivers.0.lastName",
    "vehicle.0.drivers.0.avatar",
    "vehicle.0.drivers.0.phone",
    "vehicle.0.drivers.0.email",
    "vehicle.0.drivers.0.licenseNumber",
    "vehicle.0.drivers.0.licenseExpiry",
    "vehicle.0.drivers.0.experienceYears",
    "vehicle.0.drivers.0.rating",
    "vehicle.0.drivers.0.totalTrips",
    "vehicle.0.drivers.0.active",
  ] as const,

  pricing: [
    "price.fromPrice",
    "price.toPrice",
    "price.originalFromPrice",
    "price.originalToPrice",

    "price.routePrices.0.routeId",
    "price.routePrices.0.vehicleType",
    "price.routePrices.0.basePrice",
    "price.routePrices.0.originalPrice",

    "price.routePrices.0.breakdown.baseFare",
    "price.routePrices.0.breakdown.airportFee",
    "price.routePrices.0.breakdown.parkingFee",
    "price.routePrices.0.breakdown.tollFee",
    "price.routePrices.0.breakdown.serviceFee",
    "price.routePrices.0.breakdown.taxes",
    "price.routePrices.0.breakdown.discount",
    "price.routePrices.0.breakdown.totalPrice",

    "price.routePrices.0.breakdown.includedItems",

    "price.routePrices.0.breakdown.extraFees.0.type",
    "price.routePrices.0.breakdown.extraFees.0.name",
    "price.routePrices.0.breakdown.extraFees.0.amount",
    "price.routePrices.0.breakdown.extraFees.0.required",

    "price.tripPrices.0.tripId",
    "price.tripPrices.0.finalPrice",
    "price.tripPrices.0.originalPrice",

    "price.rules.0.name",
    "price.rules.0.type",
    "price.rules.0.adjustmentType",
    "price.rules.0.value",
    "price.rules.0.minimumSpend",
    "price.rules.0.maximumDiscount",
    "price.rules.0.couponCode",
    "price.rules.0.validFrom",
    "price.rules.0.validTo",
    "price.rules.0.priority",
    "price.rules.0.combinable",
    "price.rules.0.active",
  ] as const,

  trip: [
    "trips.0.routeId",
    "trips.0.scheduleId",
    "trips.0.departureTime",
    "trips.0.estimatedArrivalTime",
    "trips.0.totalSeats",
    "trips.0.availableSeats",
    "trips.0.status",

    "trips.0.vehicleAssignment.0.vehicleId",
    "trips.0.vehicleAssignment.0.driverId",

    "availability.calendars.0.date",
    "availability.calendars.0.totalVehicles",
    "availability.calendars.0.remainingVehicles",
    "availability.calendars.0.minimumNoticeMinutes",

    "availability.locks.0.tripId",
    "availability.locks.0.vehicleId",
    "availability.locks.0.bookingId",
    "availability.locks.0.userId",
    "availability.locks.0.startTime",
    "availability.locks.0.endTime",
    "availability.locks.0.quantity",
    "availability.locks.0.expiresAt",

    "availability.blackoutDates.0.date",
    "availability.blackoutDates.0.reason",

    "capacity.maxTripsPerDay",
    "capacity.maxVehiclesPerDay",
  ] as const,

  service: [
    "flightSupport.flightNumberRequired",
    "flightSupport.airlineRequired",
    "flightSupport.terminalSupported",
    "flightSupport.arrivalFlightOnly",
    "flightSupport.departureFlightOnly",
    "flightSupport.flightTracking",
    "flightSupport.delayMonitoring",

    "meetAndGreet.available",
    "meetAndGreet.included",
    "meetAndGreet.additionalFee",
    "meetAndGreet.nameBoard",
    "meetAndGreet.airportRepresentative",
    "meetAndGreet.multilingualSupport",

    "waitingPolicy.freeWaitingMinutes",
    "waitingPolicy.airportFreeWaitingMinutes",
    "waitingPolicy.waitingFeePerHour",
    "waitingPolicy.maximumWaitingMinutes",

    "luggagePolicy.checkedBaggage",
    "luggagePolicy.cabinBaggage",
    "luggagePolicy.oversizedAllowed",
    "luggagePolicy.oversizedFee",
    "luggagePolicy.sportsEquipmentAllowed",
    "luggagePolicy.strollerAllowed",
    "luggagePolicy.wheelchairAllowed",

    "passengerRequirement.passportRequired",
    "passengerRequirement.phoneRequired",
    "passengerRequirement.emailRequired",
    "passengerRequirement.minimumPassenger",
    "passengerRequirement.maximumPassenger",

    "specialRequest.childSeat",
    "specialRequest.babySeat",
    "specialRequest.boosterSeat",
    "specialRequest.wheelchair",
    "specialRequest.petTransport",
    "specialRequest.bicycle",
    "specialRequest.skiEquipment",
    "specialRequest.golfBag",
    "specialRequest.additionalStop",
    "specialRequest.noteSupported",

    "contactInformation.hotline",
    "contactInformation.whatsapp",
    "contactInformation.telegram",
    "contactInformation.emergencyPhone",
    "contactInformation.supportEmail",
  ] as const,
};
